DEVICE: 'cpu'
NUM_WORKERS: 1
RANDOM_SEED: 42

DATA:
  TRAIN_ROOT_DIR: './data/toy_dataset/train'
  VAL_ROOT_DIR: './data/toy_dataset/val'
  IMAGE_DIR: 'images'
  MASK_DIR: 'masks'
  IMG_EXT: '.png'
  BATCH_SIZE: 2
  IMG_WIDTH: 64
  IMG_HEIGHT: 64
  CLASS_VALUES: [0, 127, 255]

MODEL:
  NAME: 'Unet'
  ENCODER_NAME: 'resnet18'

TRAIN:
  MAX_EPOCH: 20
  LR: 1e-4
